"""add_is_admin

Revision ID: 70c87474be84
Revises: 1845b45cd661
Create Date: 2026-04-17 20:15:56.646115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '70c87474be84'
down_revision: Union[str, None] = '1845b45cd661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
